@startuml
participant 管理员
管理员 -> MaterialAction : getMaterials 获取所原料信息接口
activate MaterialAction
MaterialAction -> MaterialService : findAllMaterial 获取原料方法
activate MaterialService
MaterialService -> MaterialServiceImpl : findAllMaterial 实现获取原料方法
activate MaterialServiceImpl
MaterialServiceImpl -> MaterialDao : findAllMaterial 持久层操作
activate MaterialDao
MaterialDao --> MaterialServiceImpl  : 返回原料实体集合(List)
deactivate MaterialDao
MaterialServiceImpl --> MaterialService : 返回原料实体集合或nil
deactivate MaterialServiceImpl
MaterialService --> MaterialAction : 返回原料实体集合或nil
deactivate MaterialService
MaterialAction -> ObjectModel : new 创建响应包对象
activate ObjectModel
ObjectModel --> MaterialAction : 返回创建的响应包对象，如果返回的数据为nil 则响应服务为error
deactivate ObjectModel
return 返回请求的数据信息
@enduml